#!/usr/bin/env python3
"""Build quest-creator catalog JSON, markdown galleries, and sync YAML image fields.

Run from repo root or any cwd:
  python scripts/build_catalog.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "_registry"
IMAGES = REGISTRY / "images"
PRESENTATION = ROOT / "presentation"
PRESENTATION_IMAGES = PRESENTATION / "images"
OUT_JSON = PRESENTATION / "catalog-data.json"

INVALID_FILENAME_CHARS = '<>:"/\\|?*'


def load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def sanitize_file_name(entry_id: str) -> str:
    cleaned = "".join("_" if c in INVALID_FILENAME_CHARS else c for c in entry_id).strip()
    return cleaned or "unnamed"


def image_rel_path(folder: str, entry_id: str) -> str | None:
    file_name = sanitize_file_name(entry_id) + ".png"
    absolute = IMAGES / folder / file_name
    if absolute.exists():
        return f"images/{folder}/{file_name}"
    return None


def escape_md(text: str) -> str:
    return (text or "").replace("|", "\\|")


def normalize_entry(entry_id: str, meta: Any) -> dict:
    if not isinstance(meta, dict):
        meta = {"name": str(meta) if meta is not None else entry_id}
    out = dict(meta)
    out["id"] = entry_id
    if "name" not in out or not out["name"]:
        out["name"] = entry_id
    return out


def build_entries(raw: dict, folder: str | None) -> list[dict]:
    entries: list[dict] = []
    for entry_id, meta in (raw or {}).items():
        item = normalize_entry(str(entry_id), meta)
        if folder:
            rel = image_rel_path(folder, str(entry_id))
            if rel:
                item["image"] = rel
            elif "image" in item:
                # Drop stale path if file missing
                item.pop("image", None)
        entries.append(item)
    entries.sort(key=lambda e: str(e.get("id", "")).lower())
    return entries


def write_gallery_md(
    title: str,
    folder: str | None,
    entries: list[dict],
    out_path: Path,
    extra_columns: list[tuple[str, str]] | None = None,
) -> None:
    """Write a markdown gallery. extra_columns: list of (header, field_key)."""
    extra_columns = extra_columns or []
    headers = ["id", "name"] + [h for h, _ in extra_columns] + (["preview"] if folder else [])
    lines = [
        f"# {title} gallery",
        "",
        "Auto-generated by `scripts/build_catalog.py`. Do not hand-edit — regenerate after capture.",
        "",
        "Interactive browser: [`presentation/catalog.html`](../presentation/catalog.html)",
        "",
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(["----"] * len(headers)) + "|",
    ]

    for entry in entries:
        eid = str(entry.get("id", ""))
        name = escape_md(str(entry.get("name", eid)))
        cells = [f"`{escape_md(eid)}`", name]
        for _, key in extra_columns:
            val = entry.get(key, "")
            if isinstance(val, (list, dict)):
                val = json.dumps(val, ensure_ascii=False)
            cells.append(escape_md(str(val) if val is not None else ""))
        if folder:
            img = entry.get("image")
            if img:
                cells.append(f"![{name}]({img})")
            else:
                cells.append("*(no image)*")
        lines.append("| " + " | ".join(cells) + " |")

    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path.relative_to(ROOT)} ({len(entries)} entries)")


def sync_yaml_images(yaml_path: Path, section_key: str, folder: str) -> int:
    """Insert/update `image:` under each entry when PNG exists; drop stale image lines."""
    if not yaml_path.exists():
        print(f"YAML skip (missing): {yaml_path}")
        return 0

    lines = yaml_path.read_text(encoding="utf-8").splitlines()
    output: list[str] = []
    entry_key_re = re.compile(r'^(\s{2})(?:"([^"]+)"|([^:\s][^:]*))\s*:\s*(?:#.*)?$')
    image_line_re = re.compile(r"^\s{4}image\s*:")
    section_re = re.compile(rf"^{re.escape(section_key)}\s*:")

    in_section = False
    current_id: str | None = None
    updated = 0

    for line in lines:
        trimmed = line.lstrip()
        if section_re.match(line):
            current_id = None
            in_section = True
            output.append(line)
            continue

        if in_section and line and not line[0].isspace() and not trimmed.startswith("#"):
            current_id = None
            in_section = False

        if in_section:
            key_match = entry_key_re.match(line)
            if key_match:
                current_id = key_match.group(2) or key_match.group(3).strip()
                output.append(line)
                rel = image_rel_path(folder, current_id)
                if rel:
                    output.append(f"    image: {rel}")
                    updated += 1
                continue

            if current_id and image_line_re.match(line):
                # Drop existing image lines; we rewrite after the key when PNG exists.
                continue

        output.append(line)

    yaml_path.write_text("\n".join(output) + "\n", encoding="utf-8")
    print(f"YAML image sync: {yaml_path.name} ({updated} with image)")
    return updated


def serialize_step_types(raw: dict) -> list[dict]:
    steps: list[dict] = []
    for step_id, meta in (raw or {}).items():
        if not isinstance(meta, dict):
            continue
        fields_raw = meta.get("fields") or {}
        fields = []
        for fname, fmeta in fields_raw.items():
            if isinstance(fmeta, dict):
                fields.append({"name": fname, **fmeta})
            else:
                fields.append({"name": fname, "type": str(fmeta)})
        steps.append(
            {
                "id": step_id,
                "unity_objective": meta.get("unity_objective"),
                "description": meta.get("description", ""),
                "fields": fields,
            }
        )
    return steps


def serialize_minigames(raw: dict) -> list[dict]:
    games: list[dict] = []
    for gid, meta in (raw or {}).items():
        item = normalize_entry(str(gid), meta)
        # JSON-friendly: ensure lists stay lists
        games.append(item)
    games.sort(key=lambda e: str(e.get("id", "")).lower())
    return games


def merge_items() -> dict:
    """Quest items.yaml overlaid on SoftKitty export (softkitty_items.yaml)."""
    soft = load_yaml(REGISTRY / "softkitty_items.yaml").get("softkitty_items") or {}
    quest = load_yaml(REGISTRY / "items.yaml").get("items") or {}
    merged: dict = {}
    for key, meta in soft.items():
        merged[str(key)] = dict(meta) if isinstance(meta, dict) else {"name": str(meta)}
    for key, meta in quest.items():
        q = dict(meta) if isinstance(meta, dict) else {"name": str(meta)}
        if str(key) in merged:
            # Preserve SoftKitty image/ids unless quest explicitly sets them
            base = merged[str(key)]
            for k, v in q.items():
                if v is not None and v != "":
                    base[k] = v
            merged[str(key)] = base
        else:
            merged[str(key)] = q
    return merged


def build_payload() -> dict:
    areas_raw = load_yaml(REGISTRY / "areas.yaml").get("areas") or {}
    npcs_raw = load_yaml(REGISTRY / "npcs.yaml").get("npcs") or {}
    inter_raw = load_yaml(REGISTRY / "interactables.yaml").get("interactables") or {}
    items_raw = merge_items()
    minigames_raw = load_yaml(REGISTRY / "minigames.yaml").get("minigames") or {}
    systems = load_yaml(REGISTRY / "systems.yaml")
    mapping = load_yaml(REGISTRY / "unity_mapping.yaml")

    areas = build_entries(areas_raw, "areas")
    npcs = build_entries(npcs_raw, "npcs")
    interactables = build_entries(inter_raw, "interactables")
    items = build_entries(items_raw, "items")
    minigames = serialize_minigames(minigames_raw)
    step_types = serialize_step_types(systems.get("step_types") or {})

    return {
        "title": "Quest Creator Catalog",
        "subtitle": "Open World IDs for authoring — synced to QuestWorldCatalogSet_OpenWorld",
        "canonical_pattern": mapping.get("canonical_live_pattern")
        or systems.get("canonical_live_pattern")
        or "",
        "source_of_truth": mapping.get("source_of_truth") or {},
        "counts": {
            "areas": len(areas),
            "npcs": len(npcs),
            "interactables": len(interactables),
            "items": len(items),
            "minigames": len(minigames),
            "step_types": len(step_types),
            "areas_with_image": sum(1 for e in areas if e.get("image")),
            "npcs_with_image": sum(1 for e in npcs if e.get("image")),
            "interactables_with_image": sum(1 for e in interactables if e.get("image")),
            "items_with_image": sum(1 for e in items if e.get("image")),
        },
        "areas": areas,
        "npcs": npcs,
        "interactables": interactables,
        "items": items,
        "minigames": minigames,
        "step_types": step_types,
    }


def sync_presentation_images() -> int:
    """Copy _registry/images → presentation/images so GitHub Pages (presentation root) can serve them."""
    import shutil

    if PRESENTATION_IMAGES.exists():
        shutil.rmtree(PRESENTATION_IMAGES)
    if not IMAGES.exists():
        PRESENTATION_IMAGES.mkdir(parents=True, exist_ok=True)
        return 0
    shutil.copytree(IMAGES, PRESENTATION_IMAGES)
    count = sum(1 for _ in PRESENTATION_IMAGES.rglob("*.png"))
    print(f"synced {count} PNGs -> presentation/images/")
    return count


def main() -> None:
    for sub in ("areas", "npcs", "interactables", "items"):
        (IMAGES / sub).mkdir(parents=True, exist_ok=True)

    # Sync YAML image fields from disk first so subsequent loads see them
    sync_yaml_images(REGISTRY / "areas.yaml", "areas", "areas")
    sync_yaml_images(REGISTRY / "npcs.yaml", "npcs", "npcs")
    sync_yaml_images(REGISTRY / "interactables.yaml", "interactables", "interactables")
    if (REGISTRY / "softkitty_items.yaml").exists():
        sync_yaml_images(REGISTRY / "softkitty_items.yaml", "softkitty_items", "items")

    payload = build_payload()
    sync_presentation_images()

    PRESENTATION.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT_JSON.relative_to(ROOT)}")

    write_gallery_md(
        "Areas",
        "areas",
        payload["areas"],
        REGISTRY / "areas.md",
        extra_columns=[("status", "status")],
    )
    write_gallery_md(
        "NPCs",
        "npcs",
        payload["npcs"],
        REGISTRY / "npcs.md",
        extra_columns=[("title", "title"), ("location", "location")],
    )
    write_gallery_md(
        "Interactables",
        "interactables",
        payload["interactables"],
        REGISTRY / "interactables.md",
        extra_columns=[("kind", "kind"), ("status", "status")],
    )
    write_gallery_md(
        "Items",
        "items",
        payload["items"],
        REGISTRY / "items.md",
        extra_columns=[
            ("type", "type"),
            ("softkitty_id", "softkitty_id"),
        ],
    )
    write_gallery_md(
        "Minigames",
        None,
        payload["minigames"],
        REGISTRY / "minigames.md",
        extra_columns=[
            ("category", "category"),
            ("english_focus", "english_focus"),
        ],
    )

    c = payload["counts"]
    print(
        "counts:",
        f"areas {c['areas']} ({c['areas_with_image']} img),",
        f"npcs {c['npcs']} ({c['npcs_with_image']} img),",
        f"interactables {c['interactables']} ({c['interactables_with_image']} img),",
        f"items {c['items']} ({c.get('items_with_image', 0)} img),",
        f"minigames {c['minigames']}, steps {c['step_types']}",
    )


if __name__ == "__main__":
    main()
